# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  testsolaris:
    runs-on: macos-13
    name: Test a ngrok tunnel
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          repository: libsdl-org/sdl
          ref: 'release-2.30.8'
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 14.3.1
      - name: Start SSH session
        uses: luchihoratiu/debug-via-ssh@main
        with:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
          SSH_PASS: '@abc123F'
